export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_BASKET';
export const GET_ADDED_IDS = 'GET_ADDED_IDS';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_AMOUNT_IN_CART = 'UPDATE_AMOUNT_IN_CART';
export const UPDATE_DELIVERY_METHOD = 'UPDATE_DELIVERY_METHOD';
